config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#fresh'
  get 'garden' => 'subscriptions#index'
  get 'harvest' => 'harvests#harvest'
  get 'results' => 'harvests#results'
  get 'sources' => 'sources#index', as: :sources
  get 'sources_search' => 'sources#results'
  get 'source/new' => 'sources#new', as: :source_new
  get 'unable_to_fetch' => 'sources#unable_to_fetch'
  get 'source/:id' => 'sources#show', as: :source_show
  get 'source/:id/edit' => 'sources#edit', as: :source_edit
  patch 'source/:id/edit' => 'sources#update'
  get 'sources/index' => 'sources#index'

  resources :sources do
    get 'subscribe' => 'subscriptions#subscribe'
    get 'unsubscribe' => 'subscriptions#unsubscribe'
    get 'move_garden' => 'subscriptions#update'
  end

  resources :entries, only: [] do
    get 'harvest' => 'entry_actions#harvest'
    get 'unharvest' => 'entry_actions#unharvest'
    get 'mask' => 'entry_actions#mask'
    get 'unmask' => 'entry_actions#unmask'
    get 'read' => 'entry_actions#read'
    get 'unread' => 'entry_actions#unread'
    resources :recommendations, only: [:new]
  end

  get 'harvests/more' => 'harvests#more'
  get 'pages/more' => 'pages#more'

  get 'harvests/add' => 'entry_actions#new'

  get 'contacts' => 'users#contacts'
  get 'contacts_search' => 'users#results'
  get 'befriend/:id' => 'friendships#ask', as: :befriend
  get 'accept_friendship/:id' => 'friendships#accept', as: :accept_friendship
  get 'refuse_friendship/:id' => 'friendships#refuse', as: :refuse_friendship

  get 'entries/:entry_id/recommend_to_friend/:receiver_id' => 'recommendations#recommend_to_friend', as: :recommend_to_friend
  get 'entries/:entry_id/recommend_to_team/:team_id' => 'recommendations#recommend_to_team', as: :recommend_to_team
  get 'recommendations_with/:id' => 'pages#contact', as: :recommendations_with

  post 'recommendation/:rec_id/respond' => 'messages#new', as: :respond

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

end

app/models/source.rb
require 'open-uri'

class Source < ActiveRecord::Base
  has_many :subscriptions
  has_many :entries
  has_many :entry_actions
  validates :url, uniqueness: true

  def self.to_csv
    attributes = %w{name url rss_url picture}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  def refresh

    # FETCHING FEED
    xml = HTTParty.get(self.rss_url).body
    feed = Feedjira.parse(xml)

    feed.entries.each do |e|

      # CHECKING IF ENTRIES ARE IN THE DATABASE
      if (Entry.where(media_url: e.url) == [])
        # RETRIEVING ENTRY THUMBNAIL
        image = ""
        if e.try(:media_thumbnail_url) != nil
          image = e.media_thumbnail_url
        elsif e.try(:image) != nil
          image = e.image
        elsif !Nokogiri::HTML(open(e.url)).css("meta[property='og:image']").blank?
          photo_url = Nokogiri::HTML(open(e.url)).css("meta[property='og:image']").first.attributes["content"]
          # image = URI.parse(URI.escape(photo_url))
          image = photo_url
        end
        
        # user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.854.0 Safari/535.2"
        # doc = Nokogiri::HTML(open(e.url.to_s, 'User-Agent' => user_agent, 'read_timeout' => '1' ), nil, "UTF-8")
        # unless doc.at('meta[property="og:image"]') == nil
        #   image = doc.at('meta[property="og:image"]')['content'].to_s
        # end

        # RETRIEVING ENTRY DESCRIPTION
        content = ""
        if e.try(:content) != nil
          content = e.content
        elsif e.try(:description) != nil
          content = e.description
        elsif e.try(:summary) != nil
          content = e.summary
        end

        content = ActionController::Base.helpers.strip_tags(content)
        content = CGI::unescapeHTML(content)
        content = content.truncate(300)

        # ADDING ENTRY TO THE DATABASE
        Entry.create(
          source_id: self.id, 
          title: e.title,
          content: content,
          published_date: e.published, 
          media_url: e.url,
          thumbnail_url: image)
      end
    end
  end

  def in_garden_of_user(current_user)
    s = Subscription.where(source_id: self.id, user_id: current_user.id)
    if s == []
      return nil
    else
      return s.first
    end
  end

  def entries_since(date)
    Entry.where("source_id = ? AND published_date > ?", self.id, date)
  end

  def last_entries(number)
    Entry.where(source_id: self.id).last(number)
  end

  def subscriptions_count
    self.subscriptions.count
  end

end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  require 'open-uri'
  require 'csv'
  include ApplicationHelper

  def index
    @source = Source.new
    @search = ransack_params
    if params[:filter] == 'popular'
      @sources = Source.all.sort_by {|s| s.subscriptions_count}.last(30).reverse
    else
      @sources = Source.last(30).reverse
    end
  end

  def edit
    @source = Source.find(params[:id])
    redirect_to source_show_path(@source), warning: "You are not authorized" unless current_user.admin?
  end

  def results
    @search = ransack_params
    @sources = ransack_result
    @source = Source.new
    respond_to do |format|
      format.html { render 'index.html.erb' }
    end
  end

  def show
    @filter = params[:filter]
    @search = ransack_params
    @source = Source.find(params[:id])
    @entries = []

    if @filter == 'harvested'
      @entries = Entry.joins(:entry_actions).where(entry_actions: {user_id: current_user.id, source_id: @source.id, harvested: true}).reverse_order.limit(20).to_a
    else
      @entries = @source.last_entries(30).sort_by {|p| p.created_at}.reverse
    end
  end

  def new
    @search = ransack_params
    @source = Source.new
  end

  def create
    url = source_params[:url]

    if uri?(url)

      # FETCHING URL BODY
      user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.854.0 Safari/535.2"
      begin 
        doc = Nokogiri::HTML(open(url, 'proxy' => 'http://(ip_address):(port)', 'User-Agent' => user_agent, 'read_timeout' => '10' ), nil, "UTF-8")
      rescue
        resp = HTTParty.get(url)
        doc = Nokogiri::HTML(resp.body)
      end

      # FETCHING PICTURE
      if source_params[:picture] == nil
        og_image = doc.at('meta[property="og:image"]')
        picture = ""
        unless og_image == nil
          picture = og_image['content']
        end
      else
        picture = source_params[:picture]
      end

      # FETCHING NAME
      if source_params[:name] == nil
        og_title = doc.at('meta[property="og:title"]')
        if og_title == nil
          name = doc.at('title').text
        else
          name = og_title['content']
        end
      else
        name = source_params[:name]
      end

      # FETCHING RSS URL
      if source_params[:rss_url] == nil
        rss_xml = doc.at('link[type="application/rss+xml"]')
        if rss_xml == nil
          rss_xml = doc.at('link[type="application/atom+xml"]')
        end 
        unless rss_xml == nil
          rss_url = rss_xml['href']
        end
      else
        rss_url = source_params[:rss_url]
      end

      # INSTANTIATING SOURCE
      @source = Source.new(name: name, url: url, rss_url: rss_url, picture: picture)

      respond_to do |format|
        if rss_url != nil && @source.save
          @source.refresh
          sub = Subscription.create(user_id: current_user.id, source_id: @source.id)
          sub.save
          format.html { redirect_to source_show_path(@source), notice: 'Source was successfully created.' }
          format.json { render :show_latest, status: :created, location: @source }
        else
          if @source.errors.full_messages.first == "Url has already been taken"
            original_source = Source.find_by(url: @source.url)
            format.html { redirect_to source_show_path(original_source), notice: 'Source already existing. Redirecting to it.' }
          else
            format.html { redirect_to source_new_path }
            format.json { render json: @source.errors, status: :unprocessable_entity }
          end
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to source_new_path }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @source = Source.find(params[:id])
    redirect_to source_show_path(@source), warning: "You are not authorized" unless current_user.admin?
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show_latest, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def ransack_params
      Source.ransack(params[:q])
    end

    def ransack_result
      @search.result(distinct: true)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:name, :url, :rss_url, :picture)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/edit.html.erb
<% title @source.name %>
<%= render partial: 'shared/navbar' %>
<div class="content-flex">
  <% sub = @source.in_garden_of_user(current_user) %>
  <%= render partial: 'shared/tree', locals: {sub: sub, source: @source} %>
  <h1>Éditer la source</h1>
  <hr>
  <%= simple_form_for(@source, url: source_edit_path(@source)) do |f| %>
    <%= f.input :name, label: 'Titre' %>
    <%= f.input :url, label: 'URL' %>
    <%= f.input :rss_url, label: 'RSS' %>
    <%= f.input :picture, label: 'Photo' %>
    <%= f.button :submit, 'Sauvegarder' %>
  <% end %>
</div>

app/views/sources/index.html.erb
<% title "S'abonner à une nouvelle source" %>
<%= render partial: 'shared/navbar' %>
<div class="content-flex">
  <h1>Sources d'information</h1>
  <div class="row submenu center">
    <% if params[:filter] == 'popular' %>
      <% popular = 'active' %>
      <% latest = '' %>
    <% else %>
      <% popular = '' %>
      <% latest = 'active' %>
    <% end %>
    <%= link_to sources_path, class: "#{latest}" do %>
      DÉCOUVERTES
    <% end %>
    <%= link_to sources_path(filter: 'popular'), class: "#{popular}" do %>
      POPULAIRES
    <% end %>
  </div>
  <hr>
  <% @sources.each do |source| %>
    <% sub = source.in_garden_of_user(current_user) %>
    <%= render partial: 'shared/tree', locals: {sub: sub, source: source} %>
  <% end %>
  <h1>Ajouter une source</h1>
  <hr>
  <p class="helper">Si la source que vous cherchez ne figure pas encore sur Jera, vous pouvez l'ajouter en copiant-collant le lien vers cette source dans le champ ci-dessous :</p>
  <%= simple_form_for @source do |f| %>
    <%= f.input :url, required: true, label: false, placeholder: "http://..." %>
    <%= f.button :submit, "Ajouter" %>
  <% end %>
</div>

app/views/sources/new.html.erb
<% title "Ajouter une nouvelle source" %>
<%= render partial: 'shared/navbar' %>
<div class="content-flex">
  <%= link_to sources_path, class: 'back' do %>
    Retour à la liste
  <% end %>
  <h1>Ajouter une source</h1>
  <hr>
  <p class="helper">Jera n'a pas pu ajouter automatiquement cette source, car son flux RSS est inaccessible ou inexistant.</p>
  <%= simple_form_for @source do |f| %>
    <%= f.input :name, label: 'Titre' %>
    <%= f.input :url, label: 'URL' %>
    <%= f.input :rss_url, label: 'RSS' %>
    <%= f.input :picture, label: 'Photo' %>
    <%= f.button :submit, 'Ajouter' %>
  <% end %>
</div>

app/views/sources/show.html.erb
<% title @source.name %>
<%= render partial: 'shared/navbar' %>
<div class="content-flex">
  <% sub = @source.in_garden_of_user(current_user) %>
  <%= render partial: 'shared/tree', locals: {sub: sub, source: @source} %>
  <div class="row submenu center">
    <% if @filter == 'harvested' %>
      <% harvested = 'active' %>
      <% latest = '' %>
    <% else %>
      <% harvested = '' %>
      <% latest = 'active' %>
    <% end %>
    <%= link_to source_show_path(@source), class: "#{latest}" do %>
      RÉCENTS
    <% end %>
    <%= link_to source_show_path(@source, filter: 'harvested'), class: "#{harvested}" do %>
      RÉCOLTÉS
    <% end %>
  </div>
  <hr>
  <% if @entries == [] %>
    <% if @filter == 'harvested' %>
      <span class="empty-message">Vous n'avez récolté aucun article de cette source.</span>
    <% else %>
      <span class="empty-message">Vous êtes à jour. 😌</span>
    <% end %>
  <% else %>
    <% @entries.each do |e| %>
      <%= render partial: 'shared/fruit_headless', locals: {e: e} %>
    <% end %>
  <% end %>
</div>