config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#fresh'
  get 'garden' => 'subscriptions#index'
  get 'harvest' => 'harvests#harvest'
  get 'results' => 'harvests#results'
  get 'sources' => 'sources#index', as: :sources
  get 'sources_search' => 'sources#results'
  get 'source/new' => 'sources#new', as: :source_new
  get 'unable_to_fetch' => 'sources#unable_to_fetch'
  get 'source/:id' => 'sources#show', as: :source_show
  get 'source/:id/edit' => 'sources#edit', as: :source_edit
  patch 'source/:id/edit' => 'sources#update'
  get 'sources/index' => 'sources#index'

  resources :sources do
    get 'subscribe' => 'subscriptions#subscribe'
    get 'unsubscribe' => 'subscriptions#unsubscribe'
    get 'move_garden' => 'subscriptions#update'
  end

  resources :entries, only: [] do
    get 'harvest' => 'entry_actions#harvest'
    get 'unharvest' => 'entry_actions#unharvest'
    get 'mask' => 'entry_actions#mask'
    get 'unmask' => 'entry_actions#unmask'
    get 'read' => 'entry_actions#read'
    get 'unread' => 'entry_actions#unread'
    resources :recommendations, only: [:new]
  end

  get 'harvests/more' => 'harvests#more'
  get 'pages/more' => 'pages#more'

  get 'harvests/add' => 'entry_actions#new'

  get 'contacts' => 'users#contacts'
  get 'contacts_search' => 'users#results'
  get 'befriend/:id' => 'friendships#ask', as: :befriend
  get 'accept_friendship/:id' => 'friendships#accept', as: :accept_friendship
  get 'refuse_friendship/:id' => 'friendships#refuse', as: :refuse_friendship

  get 'entries/:entry_id/recommend_to_friend/:receiver_id' => 'recommendations#recommend_to_friend', as: :recommend_to_friend
  get 'entries/:entry_id/recommend_to_team/:team_id' => 'recommendations#recommend_to_team', as: :recommend_to_team
  get 'recommendations_with/:id' => 'pages#contact', as: :recommendations_with

  post 'recommendation/:rec_id/respond' => 'messages#new', as: :respond

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:admin, :regular]
  has_one :notification
  has_many :subscriptions
  has_many :entry_actions
  has_many :memberships
  has_many :messages
  validates_uniqueness_of :username
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def friends
    friendships_as_requester = Friendship.where(user_id: self.id, status: 1)
    friendships_as_receiver = Friendship.where(friend_user_id: self.id, status: 1)
    friends = []
    friendships_as_requester.each do |f|
      friends.push(User.find(f.friend_user_id))
    end
    friendships_as_receiver.each do |f|
      friends.push(User.find(f.user_id))
    end
    return friends
  end

  def pending_friends
    pending_friends = []
    Friendship.where(user_id: self.id, status: 0).each do |f|
      pending_friends.push(User.find(f.friend_user_id))
    end
    return pending_friends
  end

  def is_friend_with?(user)
    self.friends.include?(user)
  end

  def send_friend_request_to?(user)
    self.pending_friends.include?(user)
  end

  def recs_with(user)
    if self.is_friend_with?(user)
      recs_received = Recommendation.where(receiver_id: self.id, user_id: user.id)
      recs_sent = Recommendation.where(receiver_id: user.id, user_id: self.id)
      @recommendations = (recs_sent + recs_received).sort_by {|r| r.updated_at}.reverse
    end
    return @recommendations
  end

  def new_recs
    all_recs = Recommendation.where("receiver_id = ? AND created_at > ?", self.id, self.notification.last_time_checked_contacts)
    recs = []
    all_recs.each do |r|
      if self.entry_actions.where(recommendation_id: r.id) == []
        recs.push(r)
      end
    end
    return recs
  end

  def new_responses
    all_recs = Recommendation.where("receiver_id = ? OR user_id = ? AND updated_at > ?", self.id, self.id, self.notification.last_time_checked_contacts)
    recs = []
    all_recs.each do |r|
      unless r.messages.length <= 1 || r.messages.last.user_id == self.id
        recs.push(r)
      end
    end
    return recs
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    'sources'
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def contacts
    @friends = current_user.friends

    # RECEIVED CONTACT REQUESTS
    @received_contact_requests = Friendship.where(friend_user_id: current_user.id, status: 'pending')
    
    # SENT CONTACT REQUESTS
    @sent_contact_requests = current_user.pending_friends

    @search = ransack_params

    # RECOMMENDATIONS
    @recommendations = current_user.new_recs
    
    # RESPONSES
    @responses = current_user.new_responses

    notif = current_user.notification
    notif.last_time_checked_contacts = Time.now
    notif.new_from_contacts = false
    notif.save
  end

  def results
    @search = ransack_params
    @results  = ransack_result
    if @results.include?(current_user)
      @results.to_a.delete(current_user)
    end
  end

  private
    def ransack_params
      User.ransack(params[:q])
    end

    def ransack_result
      @search.result(distinct: true)
    end
end

app/views/users/contacts.html.erb
<% title "Contacts" %>
<%= render partial: 'shared/contacts_searchbar' %>
<div class="content-flex">
  <!-- Received contact requests -->
  <% unless @received_contact_requests == [] %>
    <h1>Invitations reçues</h1>
    <hr>
    <% @received_contact_requests.each do |p| %>
      <%= render partial: 'shared/user', locals: {user: p} %>
    <% end %>
  <% end %>
  <!-- Freshly received recommendations -->
  <% unless @recommendations == [] %>
    <h1>Recommandations reçues</h1>
    <hr>
    <% @recommendations.each do |r| %>
      <% cache "recommendation-#{r.id}" do %>
        <%= render partial: 'shared/recommendation', locals: {e: r.entry, r: r, response: false} %>
      <% end %>
    <% end %>
  <% end %>
  <!-- Freshly received responses -->
  <% unless @responses == [] %>
    <h1>Réponses reçues</h1>
    <hr>
    <% @responses.each do |r| %>
      <%= render partial: 'shared/recommendation', locals: {e: r.entry, r: r, response: true} %>
    <% end %>
  <% end %>

  <% if @sent_contact_requests == [] && @friends == [] %>
    <span class="empty-message">Vous pouvez recommander vos découvertes à vos contacts, si vous pensez qu'elles leur plairont. 😋</span>
  <% else %>
    <h1>Vos contacts</h1>
    <hr>
    <% @friends.each do |f| %>
      <%= render partial: 'shared/user', locals: {user: f} %>
    <% end %>
    <!-- Received contact requests -->
    <% unless @sent_contact_requests == [] %>
      <h1>Invitations en attente</h1>
      <hr>
      <% @sent_contact_requests.each do |p| %>
        <%= render partial: 'shared/user', locals: {user: p} %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/results.html.erb
<% title "Résultats de recherche" %>
<%= render partial: 'shared/contacts_searchbar' %>
<div class="content-flex">
  <%= link_to contacts_path, class: 'back-button' do %><%= image_tag('green_arrow_left.svg') %> RETOUR<% end %>
  <h1>Résultats <% unless @search.conditions.first == nil %>"
  <%= @search.conditions.first.values.first.value %>"<% end %></h1>
  <hr>
  <% if @results == [] %>
    <p class="no_results">Aucune personne n'a été trouvée.</p>
    <p class="no_results">Invitez vos amis à s'inscrire sur Jera pour échanger les fruits de vos jardins.</p>
  <% else %>
    <% @results.each do |user| %>
      <%= render partial: 'shared/user', locals: {user: user} %>
    <% end %>
  <% end %>
</div>

app/views/users/show_friends.html.erb
<% title "Liste de mes amis" %>
<%= render partial: 'shared/friends_searchbar' %>
<div class="plant-tree-flex">
  <% if @pending == [] && @friends == [] %>
    <span class="empty-message">Vous pouvez recommander des fruits de vos jardins à vos amis, si vous pensez qu'ils leur plairont. 😋</span>
  <% else %>
    <% @pending.each do |p| %>
      <%= render partial: 'shared/user', locals: {user: p} %>
    <% end %>
    <% @friends.each do |f| %>
      <%= render partial: 'shared/user', locals: {user: f} %>
    <% end %>
  <% end %>
</div>