config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#fresh'
  get 'garden' => 'subscriptions#index'
  get 'harvest' => 'harvests#harvest'
  get 'results' => 'harvests#results'
  get 'sources' => 'sources#index', as: :sources
  get 'sources_search' => 'sources#results'
  get 'source/new' => 'sources#new', as: :source_new
  get 'unable_to_fetch' => 'sources#unable_to_fetch'
  get 'source/:id' => 'sources#show', as: :source_show
  get 'source/:id/edit' => 'sources#edit', as: :source_edit
  patch 'source/:id/edit' => 'sources#update'
  get 'sources/index' => 'sources#index'

  resources :sources do
    get 'subscribe' => 'subscriptions#subscribe'
    get 'unsubscribe' => 'subscriptions#unsubscribe'
    get 'move_garden' => 'subscriptions#update'
  end

  resources :entries, only: [] do
    get 'harvest' => 'entry_actions#harvest'
    get 'unharvest' => 'entry_actions#unharvest'
    get 'mask' => 'entry_actions#mask'
    get 'unmask' => 'entry_actions#unmask'
    get 'read' => 'entry_actions#read'
    get 'unread' => 'entry_actions#unread'
    resources :recommendations, only: [:new]
  end

  get 'harvests/more' => 'harvests#more'
  get 'pages/more' => 'pages#more'

  get 'harvests/add' => 'entry_actions#new'

  get 'contacts' => 'users#contacts'
  get 'contacts_search' => 'users#results'
  get 'befriend/:id' => 'friendships#ask', as: :befriend
  get 'accept_friendship/:id' => 'friendships#accept', as: :accept_friendship
  get 'refuse_friendship/:id' => 'friendships#refuse', as: :refuse_friendship

  get 'entries/:entry_id/recommend_to_friend/:receiver_id' => 'recommendations#recommend_to_friend', as: :recommend_to_friend
  get 'entries/:entry_id/recommend_to_team/:team_id' => 'recommendations#recommend_to_team', as: :recommend_to_team
  get 'recommendations_with/:id' => 'pages#contact', as: :recommendations_with

  post 'recommendation/:rec_id/respond' => 'messages#new', as: :respond

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

end

app/views/shared/_content.html.erb
<div class="content show">
  <div class="content-right-column">
    <div class="content-top">
      <div class="time-published source-show"><%= distance_of_time_in_words(e.created_at, Time.now) %> ago</div>
    </div>
    <div class="content-box">
      <div class="content-read" data-entry="<%= e.id %>">
        <%= link_to e.media_url, target: :blank, class: 'content-anchor' do %>
          <% if e.is_read_by_user?(current_user) %>
            <div class="read-sign">SEEN</div>
            <%= image_tag(e.thumbnail_url, class: 'content-thumbnail source-show low-opacity') %>
          <% else %>
            <div class="read-sign hidden">SEEN</div>
            <%= image_tag(e.thumbnail_url, class: 'content-thumbnail source-show') %>
          <% end %>
          <p class="content-title source-show"><%= e.title %></p>
        <% end %>
      </div>
      <p class="content-desc"><%= truncate(e.content, length: 200) %></p>
      <%= render partial: 'shared/fruit_footer', locals: {entry: e} %>
    </div>
  </div>
  <div class="content-masked hidden">
    <span>You won’t see this content again.</span>
    <%= link_to new_entry_masking_path(e), class: 'unmask', remote: :true do %>
      Unmask
    <% end %>
  </div>
  <div class="content-harvested hidden">
    <span>You have harvested this content.</span>
    <%= link_to new_entry_picking_path(e), class: 'cancel-harvest', remote: :true do %>
      Remove from harvest
    <% end %>
  </div>
</div>

app/views/shared/_content_info.html.erb
<div class="content-read" data-entry="<%= e.id %>">
  <%= link_to e.media_url, target: "_blank", class: 'content-anchor' do %>
    <% if e.is_read_by_user?(current_user) %>
      <div class="read-sign">VU</div>
      <% if e.thumbnail_url == "" || e.thumbnail_url == nil %>
        <%= image_tag('entry_img_default.png', class: 'content-thumbnail low-opacity') %>
      <% else %>
        <%= image_tag(e.thumbnail_url, class: 'content-thumbnail low-opacity') %>
      <% end %>
    <% else %>
      <div class="read-sign hidden">VU</div>
      <% if e.thumbnail_url == "" || e.thumbnail_url == nil %>
        <%= image_tag('entry_img_default.png', class: 'content-thumbnail low-opacity') %>
      <% else %>
        <%= image_tag(e.thumbnail_url, class: 'content-thumbnail') %>
      <% end %>
    <% end %>
    <p class="content-title"><%= e.title %></p>
  <% end %>
</div>
<p class="content-desc"><%= truncate(e.content, length: 200) %></p>

app/views/shared/_fresh_filter.html.erb
<div class="garden-colours">
  <div class="filter-colours">Filtrer :</div>
  <div class='filtered-colour'>
    <% if colour == 'red' %>
      🍓 <span class="underline">mes fruits rouges</span>
    <% elsif colour == 'blue' %>
      🍇 <span class="underline">mes fruits bleus</span>
    <% elsif colour == 'yellow' %>
      🍋 <span class="underline">mes fruits jaunes</span>
    <% else %>
      🌳 <span class="underline">tous mes fruits</span>
    <% end %>
    <%= image_tag('chevron_down.svg', height: '10px') %>
  </div>
  <div class="choose-colour hidden">
    <ul>
      <li><%= link_to root_path do %>🌳 tous mes fruits<% end %></li>
      <li><%= link_to root_path(colour: 'red') do %>🍓 mes fruits rouges<% end %></li>
      <li><%= link_to root_path(colour: 'blue') do %>🍇 mes fruits bleus<% end %></li>
      <li><%= link_to root_path(colour: 'yellow') do %>🍋 mes fruits jaunes<% end %></li>
    </ul>
    <%= image_tag('chevron_up.svg', height: '10px', class: 'hide-colour-selector') %>
  </div>
</div>

app/views/shared/_friend_request.html.erb
<div class="friend-request">
  <%= image_tag(f.requester.picture) %>
  <div class="right-column">
    <span><b><%= f.requester.username %></b> vous demande comme ami.</span>
    <div class="friend-request-buttons">
      <%= link_to accept_friendship_path(f), class: 'accept-friend-request', remote: :true do %>
        <span>Accepter</span>
      <% end %>
      </a>
      <%= link_to refuse_friendship_path(f), class: 'refuse-friend-request', remote: :true do %>
        <span>Refuser</span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_fruit_footer.html.erb
<% if entry.is_read_by_user?(current_user) %>
  <% entry_read = 'read hidden' %>
  <% entry_unread = 'unread' %>
<% else %>
  <% entry_read = 'read' %>
  <% entry_unread = 'unread hidden' %>
<% end %>

<div class="fruit-footer">
  <div class="fruit-footer-buttons">
    <% if entry.is_harvested_by_user?(current_user) %>
      <%= link_to entry_unharvest_path(entry, recommendation_id: rec_id), class: 'unharvest', remote: :true do %>
        Supprimer
      <% end %>
      <%= link_to entry_unread_path(entry, recommendation_id: rec_id), class: entry_unread, remote: :true do %>
        Marquer comme non lu
      <% end %>
      <%= link_to entry_read_path(entry, recommendation_id: rec_id), class: entry_read, remote: :true do %>
        Marquer comme lu
      <% end %>
      <%= link_to new_entry_recommendation_path(entry), class: 'recommend' do %>
        Partager
      <% end %>
    <% else %>
      <%= link_to entry_mask_path(entry, recommendation_id: rec_id), class: 'mask', remote: :true do %>
        Masquer
      <% end %>
      <%= link_to entry_harvest_path(entry, recommendation_id: rec_id), class: 'harvest', remote: :true do %>
        Récolter
      <% end %>
    <% end %>
  </div>
  <% if rec_id != nil %>
    <div class="messages">
      <% messages = Recommendation.find(rec_id).messages.sort_by {|m| m.created_at} %>
      <% messages.each do |m| %>
        <div class="message">
          <%= image_tag(m.user.picture, class: 'message-pic') %>
          <div class="message-column">
            <span class="message-username"><%= m.user.username %></span>
            <span class="message-text"><%= m.text %></span>
          </div>
        </div>
      <% end %>
      <div class="message hidden">
        <%= image_tag(current_user.picture, class: 'message-pic') %>
        <div class="message-column">
          <span class="message-username"><%= current_user.username %></span>
          <span class="message-text"></span>
        </div>
      </div>
    </div>
    <div class="write-response">
      <%= image_tag(current_user.picture, class: 'message-pic') %>
      <textarea onkeyup="message_textarea(this)" placeholder="Write some shit yo"></textarea>
      <a href="#" data-rec-id="<%= rec_id %>" class="message-response-button not-active">Répondre</a>
    </div>
  <% end %>
</div>

app/views/shared/_fruit_harvested.html.erb
<div class="content">
  <div class="content-left-column">
    <%= link_to source_show_path(e.source, filter: 'harvested') do %>
      <%= image_tag(e.source.picture, class: 'source-pic') %>
    <% end %>
  </div>
  <div class="content-right-column">
    <div class="content-top">
      <div class="source-title">
          <%= link_to source_show_path(e.source, filter: 'harvested') do %>
            <%= truncate(e.source.name, length: 30) %>
          <% end %>
      </div>
      <div class="time-published">il y a <%= distance_of_time_in_words(e.created_at, Time.now) %></div>
    </div>
    <div class="content-box">
      <%= render partial: 'shared/content_info', locals: {e: e} %>
      <%= render partial: 'shared/fruit_footer', locals: {entry: e, rec_id: nil} %>
    </div>
  </div>
</div>

app/views/shared/_fruit_headless.html.erb
<div class="content show">
  <div class="content-right-column">
    <div class="content-top">
      <div class="time-published source-show">il y a <%= distance_of_time_in_words(e.created_at, Time.now) %></div>
    </div>
    <div class="content-box">
      <%= render partial: 'shared/content_info', locals: {e: e} %>
      <%= render partial: 'shared/fruit_footer', locals: {entry: e, rec_id: nil} %>
    </div>
  </div>
  <div class="content-masked hidden">
    <span>Vous ne verrez plus ce fruit.</span>
    <%= link_to entry_unmask_path(e, recommendation_id: nil), class: 'unmask', remote: :true do %>
      Annuler
    <% end %>
  </div>
  <div class="content-harvested hidden">
    <span>Ajouté à votre récolte.</span>
    <%= link_to entry_unharvest_path(e, recommendation_id: nil), class: 'cancel-harvest', remote: :true do %>
      Annuler
    <% end %>
  </div>
</div>

app/views/shared/_garden_filter.html.erb
<div class="garden-colours">
  <div class="filter-colours">Filtrer :</div>
  <div class='filtered-colour'>
    <% if colour == 'red' %>
      🍓 <span class="underline">mes arbres rouges</span>
    <% elsif colour == 'blue' %>
      🍇 <span class="underline">mes arbres bleus</span>
    <% elsif colour == 'yellow' %>
      🍋 <span class="underline">mes arbres jaunes</span>
    <% else %>
      🌳 <span class="underline">tous mes arbres</span>
    <% end %>
    <%= image_tag('chevron_down.svg', height: '10px') %>
  </div>
  <div class="choose-colour hidden">
    <ul>
      <li><%= link_to garden_path do %>🌳 tous mes arbres<% end %></li>
      <li><%= link_to garden_path(colour: 'red') do %>🍓 mes arbres rouges<% end %></li>
      <li><%= link_to garden_path(colour: 'blue') do %>🍇 mes arbres bleus<% end %></li>
      <li><%= link_to garden_path(colour: 'yellow') do %>🍋 mes arbres jaunes<% end %></li>
    </ul>
    <%= image_tag('chevron_up.svg', height: '10px', class: 'hide-colour-selector') %>
  </div>
</div>

app/views/shared/_harvest_filter.html.erb
<div class="garden-colours">
  <div class="filter-colours">Filtrer :</div>
  <div class='filtered-colour'>
    <% if colour == 'red' %>
      🍓 <span class="underline">mes fruits rouges</span>
    <% elsif colour == 'blue' %>
      🍇 <span class="underline">mes fruits bleus</span>
    <% elsif colour == 'yellow' %>
      🍋 <span class="underline">mes fruits jaunes</span>
    <% else %>
      🌳 <span class="underline">tous mes fruits</span>
    <% end %>
    <%= image_tag('chevron_down.svg', height: '10px') %>
  </div>
  <div class="choose-colour hidden">
    <ul>
      <li><%= link_to harvest_path do %>🌳 tous mes fruits<% end %></li>
      <li><%= link_to harvest_path(colour: 'red') do %>🍓 mes fruits rouges<% end %></li>
      <li><%= link_to harvest_path(colour: 'blue') do %>🍇 mes fruits bleus<% end %></li>
      <li><%= link_to harvest_path(colour: 'yellow') do %>🍋 mes fruits jaunes<% end %></li>
    </ul>
    <%= image_tag('chevron_up.svg', height: '10px', class: 'hide-colour-selector') %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <%= image_tag("logo.png") %>
  <h1>Jera</h1>
</header>

app/views/shared/_navbar.html.erb
<div class="nav">
  <div class="nav-flex">
    <% if params[:controller] == 'pages' %>
      <% fresh = 'active' %>
    <% elsif params[:controller] == 'harvests' %>
      <% harvest = 'active' %>
    <% end %>
    <div class="row top-navbar">
      <div class="row nav-first-row">
        <%= image_tag(current_user.picture, class: 'profile-button') %>
        <%= link_to root_path, class: fresh do %>
          NOUVEAUTÉS
        <% end %>
        <%= link_to harvest_path, class: harvest do %>
          RÉCOLTE
          <div class="added-to-harvest">+<span class="harvest-count">0</span></div>
        <% end %>
      </div>
      <% if defined?(@search) %>
        <div class="row">
          <%= image_tag('magnifier_icon_grey.svg', class: 'magnifier-button') %>
        </div>
        <div class="row search-navbar">
          <% if harvest == 'active' %>
            <%= search_form_for @search, url: results_path(filter: params[:filter]) do |f| %>
              <%= f.search_field :entry_title_cont, class: 'nav_search_input', placeholder: 'Chercher dans votre récolte...' %>
            <% end %>
          <% else %>
            <%= search_form_for @search, url: sources_search_path do |f| %>
              <%= f.search_field :name_has_any_term, class: 'nav_search_input', placeholder: 'Chercher sur Jera...' %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="row bottom-navbar">
      <%= link_to garden_path do %>ABONNEMENTS<% end %>
      <%= link_to edit_user_registration_path do %>PARAMÈTRES<% end %>
      <%= link_to destroy_user_session_path, method: :delete do %>DÉCONNEXION<% end %>
    </div>
  </div>
</div>

app/views/shared/_profile.html.erb
<div class="profile">
  <div class="profile-flex">
    <div class="profile-background"></div>
    <div class="profile-pic-and-title">
      <% if user.picture == nil %>
        <%= image_tag('logo.png', class: 'profile-pic') %>
      <% else %>
        <%= image_tag(user.picture, class: 'profile-pic') %>
      <% end %>
      <div class="profile-name">
        <%= user.username %>
        <div class="row">
          <%= link_to edit_user_registration_path do %>
            <button class="edit-profile-button">
              Modifier mon profil
            </button>
          <% end %>
          <%= link_to friends_list_path do %>
            <button class="friends-list-button">
              Liste de mes amis
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_redbar.html.erb
<div class="redbar">
  <span><%= title %></span>
  <hr>
</div>

app/views/shared/_user.html.erb
<div class="friend-div">
  <%= image_tag(user.picture) %>
  <div class="right-column full-width">
    <span><b><%= user.username %></b></span>
    <div class="friend-request-buttons">
      <% if user.is_friend_with?(current_user) %>
        <% second_span = 'hidden' %>
        <% befriend_link = 'hidden' %>
      <% elsif current_user.send_friend_request_to?(user) %>
        <% first_span = 'hidden' %>
        <% befriend_link = 'hidden' %>
      <% else %>
        <% first_span = 'hidden' %>
        <% second_span = 'hidden' %>
      <% end %>
      <%= link_to recommendations_with_path(user.id), class: "recommendations-count #{first_span}" do %>
        <%= current_user.recs_with(user).length %> recommandations
      <% end %>
      <span class="pending <%= second_span %>">
        En attente de réponse...
      </span>
      <%= link_to befriend_path(user), class: "send-friend-request #{befriend_link}", remote: :true do %>
        Ajouter
      <% end %>
    </div>
  </div>
</div>