config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#fresh'
  get 'garden' => 'subscriptions#index'
  get 'harvest' => 'harvests#harvest'
  get 'results' => 'harvests#results'
  get 'sources' => 'sources#index', as: :sources
  get 'sources_search' => 'sources#results'
  get 'source/new' => 'sources#new', as: :source_new
  get 'unable_to_fetch' => 'sources#unable_to_fetch'
  get 'source/:id' => 'sources#show', as: :source_show
  get 'source/:id/edit' => 'sources#edit', as: :source_edit
  patch 'source/:id/edit' => 'sources#update'
  get 'sources/index' => 'sources#index'

  resources :sources do
    get 'subscribe' => 'subscriptions#subscribe'
    get 'unsubscribe' => 'subscriptions#unsubscribe'
    get 'move_garden' => 'subscriptions#update'
  end

  resources :entries, only: [] do
    get 'harvest' => 'entry_actions#harvest'
    get 'unharvest' => 'entry_actions#unharvest'
    get 'mask' => 'entry_actions#mask'
    get 'unmask' => 'entry_actions#unmask'
    get 'read' => 'entry_actions#read'
    get 'unread' => 'entry_actions#unread'
    resources :recommendations, only: [:new]
  end

  get 'harvests/more' => 'harvests#more'
  get 'pages/more' => 'pages#more'

  get 'harvests/add' => 'entry_actions#new'

  get 'contacts' => 'users#contacts'
  get 'contacts_search' => 'users#results'
  get 'befriend/:id' => 'friendships#ask', as: :befriend
  get 'accept_friendship/:id' => 'friendships#accept', as: :accept_friendship
  get 'refuse_friendship/:id' => 'friendships#refuse', as: :refuse_friendship

  get 'entries/:entry_id/recommend_to_friend/:receiver_id' => 'recommendations#recommend_to_friend', as: :recommend_to_friend
  get 'entries/:entry_id/recommend_to_team/:team_id' => 'recommendations#recommend_to_team', as: :recommend_to_team
  get 'recommendations_with/:id' => 'pages#contact', as: :recommendations_with

  post 'recommendation/:rec_id/respond' => 'messages#new', as: :respond

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

end

app/controllers/harvests_controller.rb
class HarvestsController < ApplicationController

  require 'feedjira'
  require 'open-uri'
  include ApplicationHelper

  def harvest
    @filter = params[:filter]
    @query = params[:q]

    if @filter != 'all'
      @search = current_user.entry_actions.harvested.unread.order(:created_at).reverse_order.ransack(@query)
    else
      @search = current_user.entry_actions.harvested.order(:created_at).reverse_order.ransack(@query)
    end
    @unread_count = EntryAction.where(user_id: current_user.id, harvested: true, read: false).count
    @harvested = @search.result.includes(:entry).limit(20)
    @load_more_count = load_more_count(@search.result)

    render :harvest
  end

  def results
    @query = params[:q]
    @search = current_user.entry_actions.harvested.order(:created_at).reverse_order.ransack(@query)
    @harvested = @search.result.includes(:entry).limit(20)
    @load_more_count = load_more_count(@search.result)

    render :results
  end

  def more
    @harvested = []
    if params[:all] == 'true'
      @harvested = current_user.entry_actions.harvested.order(:created_at).reverse_order.drop(params[:index].to_i)
    else
      @harvested = current_user.entry_actions.harvested.unread.order(:created_at).reverse_order.drop(params[:index].to_i)
    end
    @load_more_count = load_more_count(@harvested)
    @harvested = @harvested.first(20)
    respond_to do |format|
      format.js { render 'more_harvested.js.erb' }
    end
  end

end

app/views/harvests/_more_harvested.html.erb
<% harvested.each do |h| %>
  <% if h.recommendation_id != nil %>
    <%= render partial: 'shared/recommendation', locals: {e: h.entry, r: h.recommendation} %>
  <% else %>
    <%= render partial: 'shared/fruit_harvested', locals: {e: h.entry} %>
  <% end %>
<% end %>

app/views/harvests/harvest.html.erb
<% if params[:filter] == 'all' %>
  <% unseen = '' %>
  <% all = 'active' %>
<% else %>
  <% unseen = 'active' %>
  <% all = '' %>
<% end %>
<% load_more = "" %>
<% if @load_more_count == 0 %>
  <% load_more = "hidden" %>
<% end %>
<% title "Récolte" %>
<%= render partial: 'shared/navbar', locals: {:filter => @filter} %>
<div class="content-flex">
  <h1>Votre récolte</h1>
  <div class="row submenu">
    <%= link_to harvest_path, class: "unseen #{unseen}" do %>NON VUS <span class="unread-count">(<%= @unread_count %>)</span><% end %>
    <%= link_to harvest_path(filter: 'all'), class: "all #{all}" do %>TOUS<% end %>
  </div>
  <hr>
  <!-- To be added: adding manually entries to harvest -->
  <%= link_to harvests_add_path do %>
    <div class="add-button hidden">
      <%= image_tag("round_plus_button.svg") %>
      <span>Ajouter un élément à votre récolte</span>
    </div>
  <% end %>
  <% if @harvested == [] %>
    <% if params[:filter] == 'all' %>
      <span class="empty-message">Récoltez les articles ou vidéos qui vous intéressent parmi les dernières publications de vos abonnements. 👩‍🌾</span>
    <% else %>
      <span class="empty-message">Vous n'avez aucun article non lu : vous êtes parfaitement à jour. 😎</span>
    <% end %>
  <% else %>
    <% @harvested.each do |action| %>
      <% if action.recommendation_id != nil %>
        <%= render partial: 'shared/recommendation', locals: {e: action.entry, r: action.recommendation, response: false} %>
      <% else %>
        <%= render partial: 'shared/fruit_harvested', locals: {e: action.entry, response: false} %>
      <% end %>
    <% end %>
    <a class="load-more-harvest <%= load_more %>">
      <p class="text">Voir <%= @load_more_count %> de plus</p>
      <p class="loading hidden">Chargement<span>.</span><span>.</span><span>.</span></p>
    </a>
  <% end %>
</div>

app/views/harvests/more_harvested.js.erb
$(".content").last().after("<%= escape_javascript(render partial: 'harvests/more_harvested', locals: { harvested: @harvested } ) %>"); 
if (<%= @load_more_count %> == 0) {
  $(".load-more-harvest").addClass("hidden");
}
else {
  $(".load-more-harvest").text("Voir <%= @load_more_count %> de plus");
}

$.fn.ButtonFunction();

app/views/harvests/results.html.erb
<% title "Récolte - Recherche" %>
<%= render partial: 'shared/navbar', locals: {:filter => @filter} %>
<div class="content-flex">
  <h1>"<%= @query["entry_title_cont"] %>" - <%= pluralize(@harvested.count, 'résultat') %></h1>
  <hr>
  <% if @harvested == [] %>
    <span class="empty-message">Aucun élément de votre récolte ne correspond à votre recherche.</span>
  <% else %>
    <% @harvested.each do |action| %>
      <% if action.recommendation_id != nil %>
        <%= render partial: 'shared/recommendation', locals: {e: action.entry, r: action.recommendation, response: false} %>
      <% else %>
        <%= render partial: 'shared/fruit_harvested', locals: {e: action.entry, response: false} %>
      <% end %>
    <% end %>
  <% end %>
</div>